INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Cairo', 'القاهرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Gaber', 'سيدي جابر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Alexandria', 'الاسكندرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tanta', 'طنطا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Marsa Matruh', 'مرسى مطروح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samla', 'سملا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ras Hekmah', 'راس الحكمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fokah', 'فوكة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Galal', 'جلال', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dabaa', 'الضبعة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Abd Rahman', 'سيدي عبد الرحمن', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Alamein', 'العلمين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ameed', 'العميد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rowaysat', 'الرويسات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hammam', 'الحمام', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Burj Arab O', 'برج العرب ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Burj Arab Airport', 'مطار برج العرب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Amreyah', 'العامرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Moharam Beek', 'محرم بك', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Damanhour', 'دمنهور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Itay Barud', 'ايتاي البارود', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Zayat', 'كفر الزيات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Berket Saba', 'بركة السبع', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Quesna', 'قويسنا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Banha', 'بنها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shobra Khemah', 'شبرا الخيمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Giza', 'الجيزة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Suef', 'بني سويف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maghagha', 'مغاغة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Minya', 'المنيا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mallawi', 'ملوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Asyut', 'اسيوط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sohag', 'سوهاج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nagaa Hammadi', 'نجع حمادي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qena', 'قنا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Luxor', 'الاقصر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Edfu', 'ادفو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Ombo', 'كوم امبو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Dawar', 'كفر الدوار', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Homos', 'ابو حمص', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tawfiqiah', 'التوفيقية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Mashhour', 'ابو مشهور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Arab Raml', 'عرب الرمل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sandanhour', 'سندنهور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Toukh', 'طوخ', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qaha', 'قها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qalyoub', 'قليوب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dayrout', 'ديروط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Tij', 'ابو تيج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tima', 'طما', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tahta', 'طهطا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maragha', 'المراغة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Girga', 'جرجا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Balyana', 'البلينا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Farshut', 'فرشوط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dishna', 'دشنا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qus', 'قوص', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Armant', 'ارمنت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Esna', 'اسنا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sibaiyyah', 'السباعية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidfa', 'صدفا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Derwah', 'دروة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Wasta', 'الواسطى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Biba', 'ببا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fashn', 'الفشن', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Mazar', 'بني مزار', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Qurqas', 'ابو قرقاص', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dayr Mawas', 'دير مواس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qusiyyah', 'القوصية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manfalut', 'منفلوط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Tesht', 'ابو تشت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Monshaa', 'المنشأة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qift', 'قفط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Silwa Bahari', 'سلوا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kalabsha', 'كلابشة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Daraw', 'دراو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Matay', 'مطاي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samalut', 'سملوط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tala', 'تلا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Batanun', 'البتانون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shebeen Kom N', 'شبين الكوم ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shebeen Kom O', 'شبين الكوم ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shanawan', 'شنوان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hamoul', 'الحامول', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Minuf', 'منوف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samadun', 'سمادون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ashmun', 'اشمون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hilwasi', 'الحلواصي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hilwasi B', 'الحلواصي البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shatanof', 'شطانوف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qanatir N', 'القناطر ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qalyoub B', 'قليوب البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ayat', 'العياط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Usayrat', 'العسيرات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sharawnah', 'الشراونة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahamid', 'المحاميد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kajuj', 'كاجوج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ballana', 'بلانة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Aswan', 'اسوان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hawamdeyya', 'الحوامدية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Badrshein', 'البدرشين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mazghounah', 'المزغونة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Ammar', 'كفر عمار', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maymun', 'الميمون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ashmant', 'اشمنت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nasser', 'ناصر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Damaris', 'دماريس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manqabad', 'منقباد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maraziq', 'المرازيق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Raqqah', 'الرقة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Abo Rady', 'كوم أبو راضي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('werash', 'الورش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rous', 'الروس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nasiriyah', 'الناصرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sila', 'سيلا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Edwah', 'العدوة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Amereyat Fayoum', 'عامرية الفيوم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Aba Wakf', 'ابا الوقف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rawda', 'الروضة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bardis', 'برديس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Shousha', 'ابو شوشة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Radisia', 'الرديسية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ramadi', 'الرمادي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Port Said', 'بورسعيد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qantara Gharb', 'القنطرة غرب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ismailia', 'الاسماعيلية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Swer', 'ابو صوير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qassasin', 'القصاصين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tal Kabeer', 'التل الكبير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Hammad', 'ابو حماد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zagazig', 'الزقازيق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Menyet Qamh', 'منية القمح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Matanyah', 'المتانية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Faiyum', 'الفيوم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qotouri', 'القطورى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sheikh Haroun', 'الشيخ هارون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kima', 'كيما', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sadaka', 'الصداقة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Suds', 'سدس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Taha Bishah', 'طحا البيشة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tansa', 'طنسا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zaytoun Q', 'الزيتون ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Hidayr', 'بني حدير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Atwab', 'اطواب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Qayed', 'ميت القايد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Blida', 'البليدة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('The High Dam', 'السد العالي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mansoura', 'المنصورة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sandub', 'سندوب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shawah', 'شاوة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Baqliyyah', 'البقلية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zurayqi', 'الزريقي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shobra Qubala', 'شبرا قبالة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Senbellawein', 'السنبلاوين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Taranis Arab', 'طرانيس العرب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Barqin', 'برقين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hikal Basha', 'هيكل باشا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Shuquq', 'ابو الشقوق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Badawy', 'بدوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Saqr', 'كفر صقر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bouha', 'البوها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nazlet Khayal', 'نزلة الخيال', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Kibir', 'ابو كبير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Yassin', 'ابو ياسين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shirshimah', 'شرشيمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hihya', 'هيها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Adawyh', 'العداوية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Msalamya', 'كفر المسلمية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Harayah Raznah', 'هرية رزنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Asluji', 'العصلوجي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bardein', 'بردين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Awlad Seif', 'اولاد سيف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Belbes', 'بلبيس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tall Rozan', 'تل روزن', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bir Imarah', 'بير عمارة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Inshas', 'انشاص', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Salamant', 'سلمنت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mashtul', 'مشتول', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Monshaat Kiram', 'منشأة الكرام', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shibin Qanatir', 'شبين القناطر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Shebeen', 'كفر شبين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tahanub', 'طحانوب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Taha', 'كفر طحا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zahawiyin', 'الزهوين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nawa', 'نوى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Ramadah', 'كفر رمادة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zawya Hamraa', 'الزاوية الحمراء', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Talkha', 'طلخا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samannoud', 'سمنود', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahalla Kubra', 'المحلة الكبرى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahallat Rouh', 'محلة روح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Azhar University', 'جامعة الأزهر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Assas', 'ميت عساس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shiblanjah', 'شبلنجة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Aziziyyah', 'العزيزية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shirbin', 'شربين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Saad', 'كفر سعد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ras Khaleej', 'راس الخليج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Damietta', 'دمياط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ras Esh', 'راس العش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Halin', 'كوم حلين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahjar Abo Hammad', 'محجر ابو حماد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Serapeum', 'سرابيوم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Sultan', 'ابو سلطان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fayed', 'فايد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jenefh', 'جنيفة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sheikh Zayed', 'الشيخ زايد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('AZ Zanklun', 'الزنكلون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ghaba', 'الغابة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khalafallah', 'خلف الله', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fadadnah', 'الفدادنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bayrum', 'البيروم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Faqus', 'فاقوس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Geheinah', 'جهينة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Haj Omar', 'كفر الحاج عمر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Akyad', 'اكياد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Drakh', 'الدراكة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abaza', 'اباظة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Azzazi', 'العزازي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kabaysha', 'الكابيشة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tenh', 'التينة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Salheya', 'الصالحية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Suez', 'السويس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Menyet Sebaa', 'منية السباع', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Yazid', 'ميت يزيد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jadidah', 'الجديدة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qaraqrah', 'القراقرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sawah', 'الصوة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Basandilah', 'بسنديله', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Belkas', 'بلقاس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Biyala', 'بيلا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ibshan', 'ابشان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Taweel', 'الكوم الطويل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Ghazy', 'سيدي غازي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Murabian', 'المرابعين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Sheikh', 'كفر الشيخ', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sakha', 'سخا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahallat Mousa', 'محلة موسى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nashart', 'نشرت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qleen', 'قلين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Segin', 'سجين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ebshway', 'ابشواي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qotur', 'قطور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shin', 'الشين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qleen B', 'قلين البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Selim', 'كفر سليم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Tabluha', 'كفر طبلوها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Batanun', 'كفر البتانون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tanbadi', 'طنبدي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Sanabisah', 'كفر السنابسة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kamshush', 'كمشوش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shama', 'شما', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ramlat Injib', 'رملة الأنجب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Badr Mosque', 'جامع بدر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahallat Subk', 'محلة سبك', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Sarawah', 'كفر صراوة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shalaqan', 'شلقان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sengerg', 'سنجرج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Monshaat Sultan', 'منشأة سلطان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Iraqiyyah', 'العراقية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ashma', 'عشما', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shohada', 'الشهداء', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dinshaway', 'دنشواى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zawiyat Baqli', 'زاوية البقلى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beshtami', 'بشتامي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Amrus', 'عمروس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Mazin', 'كوم مازن', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tunub', 'طنوب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Izbat Hutaym', 'عزبة الحطيم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mishlah', 'مشلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Mishlah', 'كفر مشلة	', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qasr Nasr Din', 'قصر نصر الدين	', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Daljamun', 'الدلجمون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Warwarah', 'ورورة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Damallu', 'دملو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Hufiyyin', 'ميت الحوفيين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Barh', 'ميت بره', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Baqsa', 'بقسا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shobra Bukhum', 'شبرا بخوم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tafahna Azab', 'تفهنا العزب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Harun', 'ميت الحارون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Saad Zaghloul', 'سعد زغلول', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ismail Sedky', 'اسماعيل صدقي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mansour Basha', 'منصور باشا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zefta', 'زفتى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Ghamer', 'ميت غمر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Henash', 'سيدي حنيش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Genenet Qbaary', 'جنينة القباري', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Metras', 'المتراس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mowaslet Max', 'مواصلة المكس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Mergheb', 'سيدي مرغب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tafaro', 'التفرع', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abd Qader', 'عبد القادر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ekeingy Maryout', 'ايكنجي مريوط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maryout', 'مريوط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Baheeg', 'بهيج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gharbaniat', 'الغربانيات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gabbasat', 'الجباسات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tal Issa', 'تل العيسى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ghazal', 'غزال', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Shbeeb', 'سيدي شبيب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fardyah', 'الفردية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Atnoh', 'اطنوح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Hanosh', 'سيدي حنوش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Grawlah', 'جرولة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hadrah', 'الحضرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zahiriyyah', 'الظاهرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Souq', 'السوق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ghobrial', 'غبريال', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Raml', 'الرمل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nokrashy', 'النقراشي باشا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sidi Bishr', 'سيدي بشر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Asafra', 'العصافرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mandara', 'المندرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Montaza', 'المنتزة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Eslah', 'الاصلاح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mamurah', 'المعمورة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Naval college', 'الكلية البحرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tabya', 'الطابية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Qir Fertilizer', 'سماد ابو قير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tarh', 'الطرح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maadeyah', 'المعدية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abaadiah', 'الابعدية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Lago Idku', 'بحيرة ادكو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Damietty', 'الدمياطي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Idku', 'ادكو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Miah', 'مياح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manshyt Amel', 'منشية الأمل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sanhur', 'سنهور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hwariah', 'الهوارية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khazan', 'الخزان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rahmaniah', 'الرحمانية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Desouk', 'دسوق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Madinah', 'المدينة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shbas', 'شباس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bekatush', 'البكاتوش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Santa', 'السنطة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tafhna Ashraf', 'تفهنا الاشراف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qilishan', 'قليشان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Saft Inab', 'صفط العنب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Naqidi', 'النقيدي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Hamada', 'كوم حمادة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Bulin', 'كفر بولين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Waqid', 'واقد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Monshaat Abo Rayyah', 'منشاة ابو رية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ethaad', 'الاتحاد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tairyyah B', 'الطيرية البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Khawi', 'ابو الخاوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Modiriyat Tahrir', 'مديرية التحرير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Birijat', 'البريجات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Dawoud', 'كفر داود', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tarranah', 'الطرانة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Akhmas', 'الاخماس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khatatbah', 'الخطاطبة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Salamah', 'بني سلامة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Werdan', 'وردان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Ghaleb', 'ابو غالب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gezira wastanih', 'الجزيرة الوسطانية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qata B', 'القطا البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qata', 'القطا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Birqash', 'برقاش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Niklah', 'نكلا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zat Kom', 'ذات الكوم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manashi', 'المناشي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gelatmah', 'الجلاتمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bartas', 'برطس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ossim', 'اوسيم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Ahmar', 'الكوم الاحمر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bashtil B', 'بشتيل البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zagazig University', 'جامعة الزقازيق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tairyyah', 'الطيرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('25 Jan', '25 يناير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Burj Arab N', 'برج العرب ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Beni Helal', 'كفر بني هلال', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nefrah', 'نفرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fath', 'الفتح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gmagmun', 'جماجمون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Gazayer', 'كفر الجزاير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ezbet Godah', 'عزبة جودة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hwin', 'حوين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ibrahimiah', 'الابراهيمية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shebshir Hessah', 'شبشير الحصة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ragdiah', 'الرجدية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Henawi', 'الحناوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Monshaah Soghra', 'المنشأة الصغرى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hamidiyyah', 'الحميدية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rezqet Amay', 'رزقة أماي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Duqmayrah', 'دقميرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Salam', 'السلام', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Karykat', 'الكركات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Hajnah', 'كوم الحجنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Korma', 'ميت الكرما', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Arab', 'كفر العرب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Khalaf', 'ميت خلف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rahbayn', 'الراهبين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahallat Abo Ali Qantara', 'محلة ابو على القنطرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ghazl Mahalla', 'غزل المحلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manshyt Bakry', 'منشية البكري', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Minyat Shentena Ayash', 'منية شنتا عياش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Saft Turab', 'صفط تراب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Basatin Kafr Battikh', 'بساتين كفر البطيخ', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Battikh', 'كفر البطيخ', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tawfiqiah B', 'التوفيقية البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Saad B', 'كفر سعد البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Swalem', 'السوالم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sabreyah', 'الصبرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Saadwa', 'السعادوه', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Dabbusi', 'كفر الدبوسي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Hatabah', 'كفر الحطبه', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hag Khaleel', 'الحاج خليل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Batrah', 'بطره', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Daysat', 'ديسط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tawilah', 'الطويلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shirinqash', 'شرنقاش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Antar', 'ميت عنتر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Semad Talkha', 'سماد طلخا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gamasa', 'جمصة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Om Zein', 'ام الزين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Naghas', 'النخاس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ferdan', 'الفردان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Balah', 'البلاح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Hebeish Q', 'ميت حبيش ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shobraqas', 'شبراقاص', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Major Abd Satar', 'عبد الستار', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Monshaah Kubra', 'المنشأة الكبرى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samlaweyah', 'السملاوية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nahtay', 'نهطاي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kom Nour', 'كوم النور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dandit', 'دنديط', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Wazir', 'كفر الوزير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Qershi', 'ميت القرشي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Abo Orabi', 'ميت ابو العربي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Halaby', 'كفر الحلبي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Ashraf', 'كفر الاشراف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shibat Nakariyah', 'شيبة النكارية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Shennawy', 'كفر الشناوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manshyt Badrawy', 'منشية البدراوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Buhut', 'بهوت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Garaydah', 'كفر الجرايدة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shabanat', 'الشبانات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Saft Hinnah', 'صفط الحنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Baalwh', 'البعالوة ', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahsmh', 'المحسمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('mohamed Baghdady', 'محمد البغدادي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Gresh', 'ابو جريش', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Wasfih', 'الواصفية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nafesha', 'نفيشة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Galaa Camp', 'معسكر الجلاء', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sirs Layyanah', 'سرس الليان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Shobra Zanji', 'كفر شبرا زنجي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jarawan', 'جروان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bagour', 'الباجور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Subk Dahhak', 'سبك الضحاك', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Wusta', 'ميت الواسطى', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Istanha', 'اسطنها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Bata', 'كفر بطا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Cap', 'الكاب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Raswaa', 'الرسوة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Amer', 'عامر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ganayen', 'الجناين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shaloofh', 'شلوفة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('64 km', 'كيلو 64', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo halab', 'ابو حلب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('kasfareet', 'كسفريت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fanara', 'فنارة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kemt Fayed', 'قمة فايد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fayed N', 'فايد ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Saidia', 'السعيدية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('10th of Ramadan', '10 رمضان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ain Ghoseen', 'عين غصين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ad Dabiyyah', 'الضبعية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Agrod N', 'العجرود ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jabal Obaid', 'جبل عوبيد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jabal Jufra', 'جبل الجفرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Wadi Sail', 'وادي السيل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Robaikey', 'الربيكي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Badr', 'بدر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shorouk', 'الشروق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Darb Haj', 'درب الحاج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Obour', 'العبور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Adly Mansour', 'عدلي منصور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Danabiq', 'الدنابيق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Salamoun', 'سلامون', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shuha', 'شها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahallat Damanah', 'محلة دمنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Dafer', 'ميت ضافر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khashashnah', 'الخشاشنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dikirnis', 'دكرنس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Sharaf', 'ميت شرف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ashmoun Romman', 'اشمون الرمان', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Khouly', 'ميت الخولي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Hadid', 'ميت حديد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Asem', 'ميت عاصم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kafr Allam', 'كفر علام', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Riyad', 'الرياض', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('kurdi', 'الكردي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Salsil', 'ميت سلسيل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Marga Selsil', 'ميت مرجا سلسيل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jamaliyah', 'الجمالية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mit Khodeir', 'ميت خضير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Manzalah', 'المنزلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dar Salam', 'دار السلام', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Asafrah Manzalah', 'عصافرة المنزلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Matariyah', 'المطرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Textile factory', 'مصنع الغزل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Ahmed', 'بني أحمد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mansafis', 'منسافيس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abyuha', 'ابيوها', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Itlidim', 'اتليدم', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mahras', 'المحرص', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Massarat Malawi', 'معصرة ملوي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Amarna', 'تل العمارنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jarf', 'الجرف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sanabo', 'صنبو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fazarah', 'فزاره', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Qorah', 'بني قره', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Shakeir', 'بني شقير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Hawatkah', 'الحواتكة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nagaa Sabee', 'نجع سبع', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Hussein', 'بني حسين', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qamn Arous', 'قمن العروس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shreef Basha', 'شريف باشا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fant', 'الفنت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Malatya', 'ملاطية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qulusna', 'قلوصنا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tezment', 'تزمنت', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Awlad Ilyas', 'اولاد الياس', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shatb', 'شطب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mutiah', 'المطيعة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Baqur', 'باقور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nekhaylah', 'النخيلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mishta', 'مشطا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shatourah', 'شطورة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Banja', 'بنجا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sawamaah', 'الصوامعة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sayh', 'السايح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shandawil B', 'شندويل البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jazirat Shandawil', 'جزيرة شندويل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Balasfurah', 'بلصفورة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Isawiyyah', 'العيساوية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ahaywah', 'الأحايوه', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bindar', 'البندار', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mzata west', 'مزاتا غرب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sahel Q', 'الساحل ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Beni Hamil', 'بني حميل', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samhud', 'سمهود', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rufaa', 'رفاعة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bahjurah', 'بهجورة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khozam', 'خزام', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ayshah', 'العيايشة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shanhoria', 'الشنهورية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Sheikh Amer', 'الشيخ عامر', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Karateyah', 'الكراتية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Barahmah', 'البراهمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abnoud', 'ابنود', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ashraf', 'الاشراف', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Ashraf Qibliyyah', 'الاشراف ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jiziriyyah', 'الجزيرية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Makhadmah', 'المخادمة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Qinawiyyah', 'القناوية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Awlad Amr', 'اولاد عمرو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Samta Q', 'السمطا', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Marashdah', 'المراشدة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Faw', 'فاو', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Baseineyah', 'الياسينية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Rahmaneyah Q', 'الرحمانية ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Salmiyyah Q', 'السلمية ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Karnak', 'الكرنك', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Zayniyyah', 'الزينية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Radwania', 'الرضوانية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Wehdaa', 'الوحدة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Toud', 'الطود', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nagaa Gossor', 'نجع الجسور', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Idisat', 'العديسات', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shaghab', 'الشغب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Maelah', 'المعلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Nagaa Abo Said', 'نجع ابو سعيد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Mataenah', 'المطاعنة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Deir', 'الدير', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kelabeyah', 'الكلابية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gazirat Rageh', 'جزيرة راجح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khoy N', 'الخوي ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Phosphate N', 'الفوسفات ج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Kilh', 'الكلح', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Dawamaria', 'الدومارية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Atwani', 'العطواني', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Boghdady', 'البغدادي', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Fuzah', 'الفوزة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Tunab', 'الطوناب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Siraj', 'السراج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gaafar Sadik', 'جعفر الصادق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('sayid Said', 'السيد سعيد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Gebel Silsila', 'جبل السلسلة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Raghama', 'الرغامة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shatb B', 'الشطب البلد', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Salam Aneibah', 'السلام النوبية', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Retaj', 'الرتاج', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Jaafrah', 'الجعافرة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Aaqab', 'الاعقاب', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Aaqab Q', 'الاعقاب ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Khttarah', 'الخطارة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Shadedh', 'الشديدة', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Abo Resh Q', 'ابو الريش ق', NULL, NULL, NULL);
INSERT INTO stations (name_en, name_ar, code, location_lat, location_long) VALUES ('Bashtil', 'بشتيل المحطة', NULL, NULL, NULL);